site_name: Supernova
site_url: 'http://docs.supernovaengine.org'
site_author: 'Eduardo Dória Lima'
site_description: 'Supernova Engine documentation'

repo_name: 'supernovaengine/supernova'
repo_url: 'https://github.com/supernovaengine/supernova'
edit_uri: '../supernova-docs/edit/master/docs'

theme:
  name: 'material'
  custom_dir: 'overrides'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.png'
  #palette:
  #  primary: 'indigo'
  #  accent: 'indigo'
  feature:
    tabs: false
  features:
   - content.tabs.link

extra_css:
  - 'css/extra.css'

#extra_javascript:

extra:
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/supernovaengine/supernova'
  analytics:
    provider: google
    property: UA-113314204-2
  version: 1.0

copyright: 'Copyright &copy; 2022, Eduardo Dória (CC-BY 3.0)'

markdown_extensions:
  - md_in_html
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Introduction: 'index.md'
- Getting started:
  - Creating a basic project: 'getting-started/creating-a-basic-project.md'
  - Coordinate systems: 'getting-started/coordinate-systems.md'
  - Building:
    - Building for Windows: 'getting-started/building/building-for-windows.md'
    - Building for Linux: 'getting-started/building/building-for-linux.md'
    - Building for macOS: 'getting-started/building/building-for-macos.md'
    - Building for iOS: 'getting-started/building/building-for-ios.md'
    - Building for Android: 'getting-started/building/building-for-android.md'
    - Building for HTML5: 'getting-started/building/building-for-html5.md'
- Learning:
  - Screen scaling: 'learning/screen-scaling.md'
  - Object animation: 'learning/object-animation.md'
  - Particle system: 'learning/particle-system.md'
